# This file is auto-generated by the mezo-cli release pipeline.
# Do not edit manually.

$ErrorActionPreference = 'Stop'

$version = '0.1.0-alpha.1'
$url = "https://github.com/mezo-org/mezo-cli/releases/download/v0.1.0-alpha.1/mezo-cli-0.1.0-alpha.1-windows-x64.zip"
$checksum = 'c0ea1a5e57559bd4196277cb3d0f0ab140c2d7f5328a68d0ff96227821482135'

$packageArgs = @{
  packageName    = 'mezo-cli'
  unzipLocation  = "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)"
  url64bit       = $url
  checksum64     = $checksum
  checksumType64 = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs
