# This file is auto-generated by the mezo-cli release pipeline.
# Do not edit manually.

$ErrorActionPreference = 'Stop'

$version = '0.1.0-alpha.2'
$url = "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-windows-x64.zip"
$checksum = 'f93fdb675256e3ed51768cb4366488d830848c735a321e5dd85b776cce01b2ca'

$packageArgs = @{
  packageName    = 'mezo-cli'
  unzipLocation  = "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)"
  url64bit       = $url
  checksum64     = $checksum
  checksumType64 = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs
