# This file is auto-generated by the mezo-cli release pipeline.
# Do not edit manually.

$ErrorActionPreference = 'Stop'

$version = '0.1.0-alpha.3'
$url = "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.3/mezo-cli-0.1.0-alpha.3-windows-x64.zip"
$checksum = '673425d6793918499c1ee35048d488fd3853691b2e30115deb0e6e855712541b'

$packageArgs = @{
  packageName    = 'mezo'
  unzipLocation  = "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)"
  url64bit       = $url
  checksum64     = $checksum
  checksumType64 = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs
