# This formula is auto-generated by the mezo-cli release pipeline.
# Do not edit manually.

class MezoCli < Formula
  desc "Mezo protocol CLI"
  homepage "https://github.com/mezo-org/homebrew-tap"
  version "0.1.0-alpha.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-macos-arm64.tar.gz"
      sha256 "4990f403be3fe1aaf800119f4d127cd1fbae4371f1487da7e4fb6e466a07dddf"
    end
    on_intel do
      url "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-macos-x64.tar.gz"
      sha256 "f426889308012c4d16e0fc379748b9748290737d92d519281a17ac349fbccbee"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-linux-arm64.tar.gz"
      sha256 "7ddc99155fd1203740d06dedfa64cb17bbb9a797cdb1b85c44964fea6991f34a"
    end
    on_intel do
      url "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-linux-x64.tar.gz"
      sha256 "cf960ab60db646c7c734b2df534bdabc92935844b7a2a93604bc700a68d3f087"
    end
  end

  def install
    bin.install "mezo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mezo --version")
  end
end
