# This formula is auto-generated by the mezo-cli release pipeline.
# Do not edit manually.

class MezoCli < Formula
  desc "Mezo protocol CLI"
  homepage "https://github.com/mezo-org/mezo-cli"
  version "0.1.0-alpha.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mezo-org/mezo-cli/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-macos-arm64.tar.gz"
      sha256 "ebcee1a7a7e0e8124c85a04bea69b87b17803b280bba5d7b80b52f5425e399c6"
    end
    on_intel do
      url "https://github.com/mezo-org/mezo-cli/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-macos-x64.tar.gz"
      sha256 "c73d3e195f6264c12c6b88956d199b3b0a3fd3cadd41cbf4889ac77a146bf299"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mezo-org/mezo-cli/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-linux-arm64.tar.gz"
      sha256 "b1c22d46143f3e985e871f9caf359e8cab988a70fd016b3a2f618dfbec526492"
    end
    on_intel do
      url "https://github.com/mezo-org/mezo-cli/releases/download/v0.1.0-alpha.2/mezo-cli-0.1.0-alpha.2-linux-x64.tar.gz"
      sha256 "9d44138f26e8d8b0acb8d229ede7b28a7867068d9aa1211afccc7b7d8ebeea90"
    end
  end

  def install
    bin.install "mezo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mezo --version")
  end
end
