# This formula is auto-generated by the mezo-cli release pipeline.
# Do not edit manually.

class MezoCli < Formula
  desc "Mezo protocol CLI"
  homepage "https://github.com/mezo-org/mezo-cli"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mezo-org/mezo-cli/releases/download/v#{version}/mezo-cli-#{version}-macos-arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
    on_intel do
      url "https://github.com/mezo-org/mezo-cli/releases/download/v#{version}/mezo-cli-#{version}-macos-x64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mezo-org/mezo-cli/releases/download/v#{version}/mezo-cli-#{version}-linux-arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
    on_intel do
      url "https://github.com/mezo-org/mezo-cli/releases/download/v#{version}/mezo-cli-#{version}-linux-x64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "mezo-cli"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mezo-cli --version")
  end
end
