# This formula is auto-generated by the mezo-cli release pipeline.
# Do not edit manually.

class Mezo < Formula
  desc "Mezo protocol CLI"
  homepage "https://github.com/mezo-org/homebrew-tap"
  version "0.1.0-alpha.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.3/mezo-cli-0.1.0-alpha.3-macos-arm64.tar.gz"
      sha256 "0dd81fec3136bf852e7fef85f3fed6e58529cfb6fada3917b846f15db2a23337"
    end
    on_intel do
      url "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.3/mezo-cli-0.1.0-alpha.3-macos-x64.tar.gz"
      sha256 "1349e58489f5e0bd06fd7c601d682a60a73ffcef632e4df2532cf5ef483194bd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.3/mezo-cli-0.1.0-alpha.3-linux-arm64.tar.gz"
      sha256 "9b4ce9bacc07315df3469d5c5da3f5a540e75e20fc2998098011e5c9c66b3056"
    end
    on_intel do
      url "https://github.com/mezo-org/homebrew-tap/releases/download/v0.1.0-alpha.3/mezo-cli-0.1.0-alpha.3-linux-x64.tar.gz"
      sha256 "2438d8e91da75af1ee63d2a0fdb0b7826fe6791c0c78b0a0cbd5af3518725f6f"
    end
  end

  def install
    bin.install "mezo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mezo --version")
  end
end
